// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Post struct {
	ID     string  `json:"ID"`
	Text   string  `json:"text"`
	UserID string  `json:"userId"`
	Views  []*View `json:"views"`
	Shares int     `json:"shares"`
}

type View struct {
	UserID string  `json:"userId"`
	Time   float64 `json:"time"`
}
