// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
	Image  string `json:"image"`
}

type Post struct {
	ID            string   `json:"ID"`
	Text          string   `json:"text"`
	UserID        string   `json:"userId"`
	Views         []*View  `json:"views"`
	Shares        int      `json:"shares"`
	Reports       []string `json:"reports"`
	CreationTime  string   `json:"creationTime"`
	InitialReview bool     `json:"initialReview"`
	Image         string   `json:"image"`
}

type PostReview struct {
	Post *Post `json:"post"`
	Left int   `json:"left"`
}

type Review struct {
	PostID   string `json:"postID"`
	New      bool   `json:"new"`
	Delete   bool   `json:"delete"`
	Password string `json:"password"`
}

type View struct {
	UserID string  `json:"userId"`
	Time   float64 `json:"time"`
}
